language: node_js
node_js: lts/*
sudo: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH=$HOME/.yarn/bin:$PATH
script:
  - commitlint-travis
  - eslint --fix ./lib
  - yarn validate
  - yarn run build-storybook
install:
  - yarn install
deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: "out"
  on:
    branch: develop
env:
  matrix:
    secure: $GITHUB_TOKEN
notifications:
  email:
    - vkumar59@sapient.com
    - akakroo@sapient.com
cache:
  yarn: true
  directories:
  - node_modules
