module.exports = {
  rootDir: '../',
  setupFiles: ['<rootDir>/config/jest.setup.js'],
  moduleDirectories: ['node_modules'],
  testPathIgnorePatterns: ['<rootDir>/dist/', '<rootDir>/out/'],
  testResultsProcessor: 'jest-sonar-reporter',
  collectCoverage: true,
  coverageDirectory: '<rootDir>/reports/coverage',
  collectCoverageFrom: [
    '**lib/components/**/*.js',
    '**lib/core/**/*.js',
    '!**lib/components/**/*.mock.js',
    '!**lib/components/**/*.story.js',
    '!**lib/components/**/*.styles.js',
    '!**lib/styles/**/*.js',
    '!**/node_modules/**',
  ],
  coveragePathIgnorePatterns: [
    // exceptions.
    '/node_modules/',
    '/lib/components/molecules/Form/FieldRadioGroup/FieldRadioGroup.js',
    '/lib/components/molecules/ArticleThumbnail/ArticleThumbnail.js',
    '/lib/components/molecules/Form/FieldCheckbox/FieldCheckbox.js',
    '/lib/components/molecules/Breadcrumb/Breadcrumb.js',
    '/lib/components/molecules/Form/FieldInput/FieldInput.js',
    '/lib/components/molecules/Form/FieldCheckbox/FieldCheckbox.js',
    '/lib/components/molecules/Form/FieldRadioGroup/FieldRadioGroup.js',
    '/lib/core/utils/*.*',
  ],
  coverageReporters: ['lcov', 'json', 'text-summary'],
  coverageThreshold: {
    global: {
      branches: 40,
      functions: 60,
      lines: 70,
      statements: 70,
    },
  },
  snapshotSerializers: ['enzyme-to-json/serializer'],
  verbose: true,
  testMatch: ['<rootDir>/lib/**/*.test.js'],
};
