// @flow

export type Props = {
  pageSize: number,
  data: Array<any>,
  onPageChange: Function,
  className?: string,
  firstLabel: string,
  lastLabel: string,
  nextLabel: string,
  previousLabel: string,
  renderPaginationComponent: Function,
  totalPosts?: number,
  showNextBtn: boolean,
  showPreviousBtn?: boolean,
  showLastButton?: boolean,
  showFirstButton?: boolean,
  showLastBtn?: boolean,
  showFirstBtn?: boolean,
  currentPageAria?: string,
  paginationAriaLabel?: string,
  nextButtonAria?: string,
  previousButtonAria?: string,
  firstButtonAria?: string,
  lastButtonAria?: string,
  currentPage: number,
  pageNeighbours: number,
  gotoPageAria?: string,
};
